jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 12.7.0
      displayName: Install Node.js
    - script: yarn
      displayName: Install Packages
    - script: yarn build
      displayName: Build
    - script: yarn dist:win:nsis
      displayName: Deploy NSIS
    - script: yarn dist:win:zip
      displayName: Deploy ZIP

- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 12.7.0
      displayName: Install Node.js
    - script: yarn
      displayName: Install Packagesl
    - script: yarn build
      displayName: Build
    - script: yarn dist:mac:dmg
      displayName: Deploy DMG
    - script: yarn dist:mac:zip
      displayName: Deploy ZIP
