jobs:
- job: Windows
  pool:
    vmImage: VS2017-Win2016
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.16.0
      displayName: Install Node.js
    - script: yarn
      displayName: Yarn Install
    - script: yarn dist --win
      displayName: Yarn Dist

- job: macOS
  pool:
    vmImage: macOS 10.13
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.16.0
      displayName: Install Node.js
    - script: yarn
      displayName: Yarn Install
    - script: yarn dist --win
      displayName: Yarn Dist
